run:
  deadline: 5m
  tests: true

linters:
  enable:
    - revive
    - gofmt
    - staticcheck
    - vet
    - misspell
    - ineffassign
    - deadcode
    - errcheck
    - structcheck
    - unused
    - varcheck
  enable-all: false
