version: 2.1
jobs:
  # build:
  #   docker:
  #     - image: circleci/golang:1.12
  #   working_directory: /go/src/github.com/spothero/periodic
  #   steps:

  lint:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/spothero/periodic
    steps:
      - checkout
      - run: make bootstrap
      - run: make vendor
      - run: make lint
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/spothero/periodic
    steps:
      - checkout
      - run: make vendor
      - run: gotestsum --junitfile tests.xml github.com/spothero/periodic -- -race -coverprofile=coverage.txt -covermode=atomic
      # CircleCI likes tests results to be in sub-directories for naming
      - run: mkdir -p /tmp/test-results/unit && cp tests.xml /tmp/test-results/unit/tests.xml
      - store_test_results:
          path: /tmp/test-results
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  test_and_lint:
    jobs:
      - lint
      - test
